"""explicit_priority_and_coverage

Revision ID: ba0170a97753
Revises: 124ce60f176e
"""

from alembic import op
import sqlalchemy as sa


revision = "ba0170a97753"
down_revision = "124ce60f176e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("classification", sa.String(length=40), nullable=True))
    op.add_column("jobs", sa.Column("coverage", sa.Float(), nullable=True))
    op.create_index(op.f("ix_jobs_classification"), "jobs", ["classification"], unique=False)
    # PostgreSQL and modern SQLite both support the JSON ->> operator.
    op.execute(
        "UPDATE jobs SET classification = (SELECT classification FROM match_analyses WHERE match_analyses.job_id = jobs.id ORDER BY created_at DESC LIMIT 1), coverage = (SELECT CAST(result ->> 'coverage' AS FLOAT) FROM match_analyses WHERE match_analyses.job_id = jobs.id ORDER BY created_at DESC LIMIT 1) WHERE score IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_classification"), table_name="jobs")
    op.drop_column("jobs", "coverage")
    op.drop_column("jobs", "classification")
    # ### end Alembic commands ###
