"""persistent_search_scheduling

Revision ID: c0c9f428dbf3
Revises: c301_personal_lifecycle
"""

from alembic import op
import sqlalchemy as sa


revision = "c0c9f428dbf3"
down_revision = "c301_personal_lifecycle"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_heartbeats",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dashboard_visits",
        sa.Column("visited_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_dashboard_visits_created_at"), "dashboard_visits", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_dashboard_visits_user_id"), "dashboard_visits", ["user_id"], unique=False
    )
    op.create_table(
        "saved_job_searches",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("location", sa.String(length=240), nullable=False),
        sa.Column("work_models", sa.JSON(), nullable=False),
        sa.Column("seniority", sa.String(length=40), nullable=False),
        sa.Column("salary_min", sa.Float(), nullable=True),
        sa.Column("providers", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cadence_hours", sa.Integer(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_status", sa.String(length=30), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_result", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_job_searches_created_at"), "saved_job_searches", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_saved_job_searches_next_run_at"),
        "saved_job_searches",
        ["next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_saved_job_searches_user_id"), "saved_job_searches", ["user_id"], unique=False
    )
    op.add_column("tasks", sa.Column("available_at", sa.DateTime(), nullable=True))
    op.add_column("tasks", sa.Column("active_key", sa.String(length=100), nullable=True))
    op.create_index("ix_tasks_active_key", "tasks", ["active_key"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError(
        "Restore a verified backup in another database; scheduling history must be preserved."
    )
